# Python 3
# Program to strip the APs that devices are reaching out to from a csv generated by airodump-ng
# By ariakis

import sys, os, csv

# Initialise variables
separator = "Station MAC"
doPrints = False
counter = 1



# Navigate to the correct directory and open files for read/write
inpFilename = os.path.abspath(os.path.dirname( __file__ )) + "/" + sys.argv[1]
inputFile = open(inpFilename,"r")


def maclookup(mac,ouiFile):
	mac = mac.replace(':','')
	mac = mac[0:6]

	with open(ouiFile,'r') as ouis:
		for line in ouis:
			if line[12:19] == 'base 16':
#				print("Device mac:",mac,"-","Vendor mac:",line[0:6])
				if line[0:6] == mac:
					vendor = line[22:-1]
					return vendor
		return 'n/a'

# Scroll to clients

reader = csv.reader(inputFile)

for row in reader:
	if len(row) > 0: # if line not blank to prevent errs (first line is blank always)
		if row[0] == separator: # only scan APs, not clients
			break


# Main read loop

APList = []

for row in reader:
	rowlength = len(row)

	if rowlength > 6 and row[6] != '': # if line not blank
		APs = row[6:rowlength]

#		print("Client reaching for " + str(len(APs)))

		for AP in APs:
			if AP not in APList:
				station = row[0]

				vendor = maclookup(station,'oui.txt')

				print(str(counter)+': ' + row[1] + ' - ' + station + ' (' + vendor + ')' + ' - ' + AP)
				APList.append(AP)

				counter += 1

inputFile.close()
