# Python 3
# Program to strip the APs that devices are reaching out to from a csv generated by airodump-ng
# By ariakis

import sys, os, csv

# Initialise variables
separator = "Station MAC"
doPrints = False
counter = 1


# Navigate to the correct directory and open files for read/write
inpFilename = os.path.abspath(os.path.dirname( __file__ )) + "/" + sys.argv[1]
inputFile = open(inpFilename,"r")


def maclookup(mac,ouiFile):
	mac = mac.replace(':','')
	mac = mac[0:6]

	with open(ouiFile,'r') as ouis:
		for line in ouis:
			if line[12:19] == 'base 16':
				if line[0:6] == mac:
					vendor = line[22:-1]
					return vendor
		return 'n/a'

# Scroll to clients

reader = csv.reader(inputFile)

APlist = {
	'WEP' : [],
	'WPA' : [],
	'WPA2' : [],
	'WPAboth' : [],
	'OPN' : []
}

for row in reader:
	if (len(row) > 0): # if line not blank to prevent errs (first line is blank always)
		if row[0] == separator: # only scan APs, not clients
			break
		elif row[0] == 'BSSID': # if header row
			pass
		elif '-1' in str(row[4]): # sometimes airodump messes up and doesn't collect properly - ignore these instances
			pass
		else:
			station = row[0]
			#vendor = maclookup(station,'oui.txt')
			security = row[5][1:]
			SSID = row[13][1:]
			timeSeen = row[1]

			if security == 'WEP':
				APlist['WEP'].append([station,SSID])
			elif security == 'WPA':
				APlist['WPA'].append([station,SSID])
			elif security == 'WPA2':
				APlist['WPA2'].append([station,SSID])
			elif security == 'WPA2 WPA':
				APlist['WPAboth'].append([station,SSID])
			elif security == 'OPN':
				APlist['OPN'].append([station,SSID])
			else:
				print("unknown type",security)
				exit()

#			print(str(counter)+': ' + station + ' - ' + SSID + ' (' + security + ')')


			counter += 1

printed = []
for key in APlist:
	print(key + '(' + str(len(APlist[key])) + ')')
	print()
	print('-'*20)
	print()
	for AP in APlist[key]:
		if (AP[1] not in printed) and (AP[1] != ''):
			print(AP[1],end=', ')
			printed.append(AP[1])
	print()
	print()
	print('-'*20)
	print()

inputFile.close()
